### ISSUE TITLE
no highway shows up

### ISSUE THREAD

**Issue by silverhed** [Encore-Developers/Encore#17]
im on linux mint 21.3 x86_64
![image](https://github.com/Encore-Developers/Encore/assets/84687911/626f5537-2679-43f4-8594-058d55d5502e)

**Comment by 3drosalia** [comment]
yeah this is an issue with render textures not working on linux. im not quite sure how to fix it on linux though. wine doesnt work either

**Comment by 3drosalia** [comment]
ty for reporting though, thought it was an issue on my Deck

**Comment by silverhed** [comment]
> yeah this is an issue with render textures not working on linux. im not quite sure how to fix it on linux though. wine doesnt work either

wine works for me though

**Comment by mtolly** [comment]
I'm seeing this on my laptop (Intel integrated graphics) but it works fine on my desktop (Nvidia card), both running Mint (Cinnamon).

The issue seems to be something with how the render textures are resized/replaced. I edited it to launch the window at a default resolution and disabled all of the render texture resize code, and it almost works, I think it's just at half size because I'm running at high DPI (150% scale but maybe the game renders at 200%?). But of course it stays the same size when resizing the window.

https://github.com/mtolly/Encore/commit/7534e14318db579c68af9ee88b99efc20915f224

![Screenshot from 2024-08-07 20-56-34](https://github.com/user-attachments/assets/f87fcf70-4b6c-4f69-b8a0-90e2c190c245)

**Comment by 3drosalia** [comment]
huh. i wonder if this could potentially be an issue with the raylib GetScreenHeight/GetScreenWidth (and GetMonitorHeight/GetMonitorWidth) methods, because I know that Encore also struggles with those methods (see #3 )

**Comment by 3drosalia** [comment]
Ok, actually, I might have just fixed this in the recent commit [400b0e5](https://github.com/Encore-Developers/Encore/commit/400b0e55059eb2e5c3a5efc1fde7bab375e472c9). I'd highly suggest trying this commit when it builds, and reporting back here if it really works. 

Before commit:
![image](https://github.com/user-attachments/assets/1d1f2700-7d25-4b17-9a63-63c107097501)

After commit:
![image](https://github.com/user-attachments/assets/afe8b964-da5d-4412-973d-a1743e9f0e8d)

**Comment by tposejank** [comment]
For Linux peeps with this issue, try [this Workflow Run](https://github.com/Encore-Developers/Encore/actions/runs/10399837982) which uses the commit 400b0e5 previously mentioned

**Comment by 3drosalia** [comment]
awesome!!!
